---
- name: Make sure etcd certificate vars are set
  fail:
    msg: "etcd certificates weren't slurped. Aborting ..."
  when: etcd_ca_cert is not defined or etcd_client_cert is not defined or etcd_client_key is not defined

- name: Make sure Flanneld etcd certs dir exists
  file:
   state: directory
   path: "{{ flannel_etcd_certs_dir }}"
   mode: "o-rwx"
   owner: root
   group: root

- name: Copy etcd certificates to nodes
  copy:
    dest: "{{ item.filename }}"
    content: "{{ item.contents }}"
    group: root
    owner: root
    mode: "0440"
  with_items:
    - filename: "{{ flannel_etcd_ca_file }}"
      contents: "{{ etcd_ca_cert }}"
    - filename: "{{ flannel_etcd_cert_file }}"
      contents: "{{ etcd_client_cert }}"
    - filename: "{{ flannel_etcd_key_file }}"
      contents: "{{ etcd_client_key }}"
