---
# This playbook deploys a kubernetes cluster
# with the default addons.

- hosts: all
  gather_facts: false
  become: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# DNS resolution of the cluster nodes is setup on every node
- hosts: all
  become: yes
  tasks:
    - name: Add DNS resolution entries to all hosts in the cluster
      lineinfile:
        path: /etc/hosts
        state: present
        line: "{{hostvars[item]['ansible_' + cluster_network_interface]['ipv4']['address']}} {{hostvars[item]['ansible_hostname']}}"
      with_items: "{{ groups['masters'] + groups['nodes'] + groups['etcd'] }}"
  tags:
    - prepare-hosts

# Install etcd
- include: deploy-etcd.yml
  tags:
    - deploy-etcd

# Install docker
- include: deploy-docker.yml
  tags:
    - deploy-docker

# install flannel
- hosts:
    - masters
    - nodes
  become: yes
  roles:
    - { role: etcd-certs, when: flannel_etcd_use_certs|default(false) }
    - { role: flannel, when: networking == 'flannel' }
  tags:
    - network-service-install

# install opencontrail
- hosts: all
  become: yes
  roles:
    - { role: opencontrail, when: networking == 'opencontrail'}
  tags:
    - network-service-install

# install contiv netmaster
- hosts: masters
  become: yes
  roles:
    - { role: contiv, contiv_role: netmaster, when: networking == 'contiv' }

# install kube master services
- include: deploy-master.yml
  tags:
    - kube-master

# launch addons, like dns
- include: deploy-addons.yml
  tags:
    - kube-addons

# install kubernetes on the nodes
- include: deploy-node.yml
  tags:
    - kube-node

# provision opencontrail once the services are operational
- hosts:
    - masters[0]
    - nodes
  become: yes
  roles:
    - { role: opencontrail-provision, when: networking == 'opencontrail' }
  tags:
    - network-service-config

# install contiv netplugin
- hosts: nodes
  become: yes
  roles:
    - { role: contiv, contiv_role: netplugin, when: networking == 'contiv' }
